version: 2

sources:
  - name: erp_aw
    description: The adventure works postgresSQL database replica.
    schema: adventure_works_el
    tables:

      - name: address
        description: Street address information for customers, employees, and vendors.
        columns:
          - name: addressid
            description: Primary key for Address records.
            tests:
              - unique
              - not_null

          - name: addressline1
            description: Address information.
          
          - name: city
            description: Name of the city.
            tests:
              - not_null

          - name: postalcode
            description: Postal code for the street address.
          
          - name: stateprovinceid
            description: Unique identification number for the state or province. Foreign key to StateProvince table.


      - name: countryregion
        description: Lookup table containing the ISO standard codes for countries and regions.
        columns:
          - name: countryregioncode
            description: ISO standard code for countries and regions.
            tests:
              - unique
              - not_null
          
          - name: name
            description: Country or region name.

      
      - name: creditcard
        description: Customer credit card information.
        columns:
          - name: creditcardid
            description: Primary key for CreditCard records.
            tests:
              - unique
              - not_null
          
          - name: cardtype
            description: Credit card type.

          - name: expmonth
            description: Credit card expiration month.

          - name: expmonth
            description: Credit card expiration year.


      - name: customer
        description: Current customer information. Also see the Person and Store tables.
        columns:
          - name: customerid
            description: Primary key.
            tests:
              - unique
              - not_null
          
          - name: personid
            description: Foreign key to Person.

          - name: territoryid
            description: ID of the territory in which the customer is located. Foreign key to SalesTerritory.

          - name: storeid
            description: Foreign key for store.businessentityid


      - name: person
        description: Human beings involved with AdventureWorks employees, customer contacts, and vendor contacts.
        columns:
          - name: businessentityid
            description: Primary key for Person records.
            tests:
              - unique
              - not_null
          
          - name: persontype
            description: Primary type of person (SC = Store Contact, IN = Individual (retail) customer, SP = Sales person, EM = Employee (non-sales), VC = Vendor contact, GC = General contact).

          - name: namestyle
            description: 0 = The data in FirstName and LastName are stored in western style (first name, last name) order.  1 = Eastern style (last name, first name) order.

          - name: title
            description: A courtesy title. For example, Mr. or Ms.

          - name: firstname
            description: First name of the person.

          - name: middlename
            description: Middle name or middle initial of the person.

          - name: lastname
            description: Last name of the person. 

          - name: suffix
            description: Surname suffix. For example, Sr. or Jr.


      - name: product
        description: Products sold or used in the manfacturing of sold products.
        columns:
          - name: productid
            description: Primary key for Product records.
            tests:
              - not_null
              - unique

          - name: productmodelid
            description: Product is a member of this product model. Foreign key to ProductModel.ProductModelID.
    
          - name: idproductsubcategoryid
            description: Product is a member of this product subcategory. Foreign key to ProductSubCategory.ProductSubCategoryID.
    
          - name: name
            description: Name of the product.
    
          - name: productnumber
            description: Unique product identification number.
    
          - name: color
            description: Product color.
    
          - name: size
            description: Product size.
    
          - name: makeflag
            description: 0 = Product is purchased, 1 = Product is manufactured in-house.
    
          - name: listprice
            description: Selling price.
    
          - name: weight
            description: Product weight.
      
            
      - name: productcategory
        description: High-level product categorization.
        columns:
          - name: productcategoryid
            description: Primary key for ProductCategory records.
            tests:
              - unique
              - not_null

          - name: name
            description: Category description.


      - name: productsubcategory
        description: Product subcategories. See ProductCategory table.
        columns:
          - name: productsubcategoryid
            description: Primary key for ProductSubcategory records.
            tests:
              - unique
              - not_null

          - name: productcategoryid
            description: Product category identification number. Foreign key to ProductCategory.ProductCategoryID.

          - name: name
            description: Subcategory description.

               
      - name: salesorderdetail
        description: Individual products associated with a specific sales order.
        columns:
          - name: salesorderid
            description: Primary key. Foreign key to SalesOrderHeader.
            tests:
              - not_null

          - name: salesorderdetailid
            description: Primary key. One incremental unique number per product sold.
            tests:
              - unique
              - not_null

          - name: orderqty
            description: Quantity ordered per product.

          - name: productid
            description: Product sold to customer. Foreign key to Product.
            
          - name: unitprice
            description: Selling price of a single product.
          
          - name: unitpricediscount
            description: Discount amount.


      - name: salesorderheader
        description: General sales order information.
        columns:
          - name: salesorderid
            description: Primary key of the salesorderheader table.
            tests:
              - unique
              - not_null

          - name: orderdate
            description: Dates the sales order was created.
        
          - name: status
            description: Order current status. 1 = In process; 2 = Approved; 3 = Backordered; 4 = Rejected; 5 = Shipped; 6 = Cancelled
    
          - name: customerid
            description: Customer identification number. Foreign key to Customer.
    
          - name: salespersonid
            description: Sales person who created the sales order. Foreign key to SalesPerson.
    
          - name: territoryid
            description: Territory in which the sale was made. Foreign key to SalesTerritory.

          - name: billtoaddressid
            description: Customer billing address. Foreign key to Address.
    
          - name: creditcardid
            description: Credit card identification number. Foreign key to CreditCard.

            
      - name: salesorderheadersalesreason
        description: Cross-reference table mapping sales orders to sales reason codes.
        columns:
          - name: salesorderid
            description: Primary key. Foreign key to SalesOrderHeader.
            tests:
              - not_null
          
          - name: salesreasonid
            description: Primary key. Foreign key to SalesReason.


      - name: salesreason
        description: Lookup table of customer purchase reasons.
        columns:
          - name: salesreasonid
            description: Primary key for SalesReason records.
            tests:
              - unique
              - not_null
          
          - name: name
            description: Sales reason description.
          
          - name: reasontype
            description: Category the sales reason belongs to.


      - name: stateprovince
        description: State and province lookup table.
        columns:
          - name: stateprovinceid
            description: Primary key for StateProvince records.
            tests:
              - unique
              - not_null
          
          - name: stateprovincecode
            description: ISO standard state or province code.

          - name: countryregioncode
            description: ISO standard country or region code. Foreign key to CountryRegion.
          
          - name: name
            description: State or province description. 
          
          - name: territoryid
            description: ID of the territory in which the state or province is located. Foreign key to SalesTerritory.


     
      - name: store
        description: Customers (resellers) of Adventure Works products.
        columns:
          - name: businessentityid
            description: Primary key. Foreign key to Customer.BusinessEntityID.
            tests:
              - unique
              - not_null
          
          - name: name
            description: Name of the store.

          - name: salespersonid
            description: ID of the sales person assigned to the customer. Foreign key to SalesPerson.BusinessEntityID.

          - name: demographics
            description: Demographic informationg about the store such as the number of employees, annual sales and store type.
